apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-viuc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-viuc
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-viuc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-viuc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-viuc
    spec:
      containers:
      - image: quay.io/quay_xjiang/rhtap-demo-gjnx-tenant/e2e-nodejs/nodejs-health-check-viuc@sha256:fb99079d8a4f9e69b17e19ac4d3068fbab403d0014989a097f5a78a002ac9f81
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
